export const USERINFO_EDIT_REQUEST = 'USERINFO_EDIT_REQUEST';
export const USERINFO_EDIT_SUCCESS = 'USERINFO_EDIT_SUCCESS';
export const USERINFO_EDIT_FAIL = 'USERINFO_EDIT_FAIL';

export const USERINFO_LOAD_REQUEST = 'USERINFO_LOAD_REQUEST';
export const USERINFO_LOAD_SUCCESS = 'USERINFO_LOAD_SUCCESS';
export const USERINFO_LOAD_FAIL = 'USERINFO_LOAD_FAIL';
