export const LOAD_BIDS_REQUEST = 'LOAD_BIDS_REQUEST';
export const LOAD_BIDS_SUCCESS = 'LOAD_BIDS_SUCCESS';
export const LOAD_BIDS_FAILURE = 'LOAD_BIDS_FAILURE';

export const STORE_BID_REQUEST = 'STORE_BID_REQUEST';
export const STORE_BID_SUCCESS = 'STORE_BID_SUCCESS';
export const STORE_BID_FAILURE = 'STORE_BID_FAILURE';
