export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const POST_INDEX_REQUEST = 'POST_INDEX_REQUEST';
export const POST_INDEX_SUCCESS = 'POST_INDEX_SUCCESS';
export const POST_INDEX_FAIL = 'POST_INDEX_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const PRODUCT_STORE_REQUEST = 'PRODUCT_STORE_REQUEST';
export const PRODUCT_STORE_SUCCESS = 'PRODUCT_STORE_SUCCESS';
export const PRODUCT_STORE_FAIL = 'PRODUCT_STORE_FAIL';