export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const POST_INDEX_REQUEST = 'POST_INDEX_REQUEST';
export const POST_INDEX_SUCCESS = 'POST_INDEX_SUCCESS';
export const POST_INDEX_FAIL = 'POST_INDEX_FAIL';